using TinyProc.Assembler;
using TinyProc.Application;

class Program
{
    // Note: This Main function should only be called when intending to run in CLI mode.
    static void Main(string[] args)
    {
        // Enable full logging when running from CLI mode
        // TODO: Make this configurable via command-line arguments
        Logging.SuppressDebugMessages = false;
        Logging.SuppressInfoMessages = false;
        Logging.SuppressWarningMessages = false;
        Logging.SuppressErrorMessages = false;

        Logging.LogInfo(
            $"TinyProc ver. {GlobalData.TINYPROC_PROGRAM_VERSION_STR} " +
            $"Processor revision {GlobalData.PROCESSOR_REVISION_VERSION_STR}");

        Logging.LogDebug($"Arguments: {args.Length}");

        if (args.Length != 2
            || (!args[0].Equals("--assemble") && !args[0].Equals("--run")))
        {
            Logging.LogError(
                "Usage:\n" +
                "--assemble <Source file> : Creates a binary executable file in the same directory.\n" +
                "--run <Executable file> : Runs the executable file generated by the --assemble command.");
            return;
        }

        if (args[0].Equals("--assemble"))
        {
            string sourceFilePath = args[1];
            Logging.LogInfo($"Assembling source file {sourceFilePath}");
            if (sourceFilePath.Trim().EndsWith(".lltp32.asm"))
                Logging.LogWarn("Warning: Source file name does not end with standard suffix \".lltp32.asm\".");

            string assemblyCode = File.ReadAllText(sourceFilePath);
            uint[] MAIN_PROGRAM = Assembler.AssembleToMachineCode(assemblyCode);

            ExecutableWrapper programWrapper = new(MAIN_PROGRAM);

            string outputBinaryFilePath = sourceFilePath + ".bin";
            if (sourceFilePath.EndsWith(".asm"))
                outputBinaryFilePath = sourceFilePath[..^4] + ".bin";
            programWrapper.WriteExecutableBinaryToFile(outputBinaryFilePath);

            return;
        }

        if (args[0].Equals("--run"))
        {
            string executableFilePath = args[1];

            ExecutableWrapper programWrapper = new(executableFilePath);

            Console.CancelKeyPress += delegate
            {
                ExitClean();
            };

            ExecutionContainer.Initialize(programWrapper);

            // If this program is at this stage, it is probably running in CLI mode.
            Logging.LogInfo("Program ready to execute. Press enter to start first cycle. Press \"q\" to exit.");
            while (true)
            {
                if (Console.ReadLine() == "q")
                    break;
                ExecutionContainer.INSTANCE0.StepSingleCycle();
            }
            ExitClean();
        }
    }

    private static void ExitClean()
    {
        Logging.LogInfo("Leaving cycle loop and exiting...");
    }
}